// Code generated by crd2go. DO NOT EDIT.

package v1

import metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"

func init() {
	SchemeBuilder.Register(&DNSZone{})
	SchemeBuilder.Register(&DNSZoneList{})
}

// +k8s:deepcopy-gen:interfaces=k8s.io/apimachinery/pkg/runtime.Object
// +kubebuilder:object:root=true
// +kubebuilder:resource

type DNSZone struct {
	metav1.TypeMeta `json:",inline"`

	metav1.ObjectMeta `json:"metadata,omitempty"`

	Spec DNSZoneSpec `json:"spec,omitempty"`

	Status DNSZoneStatus `json:"status,omitempty"`
}

type DNSZoneSpec struct {
	// V0_0_15 The spec of the dnszone resource for version v0_0_15.
	V0_0_15 *DNSZoneSpecV0_0_15 `json:"v0_0_15,omitempty"`
}

type DNSZoneSpecV0_0_15 struct {
	// Entry The entry fields of the dnszone resource spec. These fields can be set for
	// creating and updating dnszones.
	Entry *Entry `json:"entry,omitempty"`
}

type Entry struct {
	Kind string `json:"kind"`

	Name string `json:"name"`

	Nameservers *[]string `json:"nameservers,omitempty"`
}

type DNSZoneStatus struct {
	// Conditions Represents the latest available observations of a resource's current
	// state.
	Conditions *[]metav1.Condition `json:"conditions,omitempty"`

	// V0_0_15 The last observed Atlas state of the dnszone resource for version
	// v0_0_15.
	V0_0_15 *DNSZoneStatusV0_0_15 `json:"v0_0_15,omitempty"`
}

type DNSZoneStatusV0_0_15 struct {
	Id *string `json:"id,omitempty"`
}

// +kubebuilder:object:root=true
type DNSZoneList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []DNSZone `json:"items"`
}

// GetConditions for DNSZone
func (ds *DNSZone) GetConditions() []metav1.Condition {
	if ds.Status.Conditions == nil {
		return nil
	}
	return *ds.Status.Conditions
}
